cache: npm
install:
  - npm --prefix functions install
  - npm --prefix hosting/apply install
  - npm --prefix hosting/qt install
language: node_js
node_js:
  - 8.15.1
script:
  - npm --prefix functions run lint
  - npm --prefix hosting/apply run lint
  - npm --prefix hosting/apply run test
  - npm --prefix hosting/qt run lint
  - npm --prefix hosting/qt run test
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    npm install -g firebase-tools &&
    firebase deploy --token $FIREBASE_TOKEN --project default --force
