cache: npm
before_install:
  - npm install -g firebase-tools
install:
  - npm install
  - npm --prefix ./functions install ./functions
language: node_js
node_js:
  - 8.14.0
script:
  - npm run lint
  - npm test
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    firebase deploy --token $FIREBASE_TOKEN --project default --force
