
name: Firestore Rules
'on':
  pull_request:
    paths:
    - 'database/firestore.rules'
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm ci
      # TODO reuse the setup steps rather than replaying across jobs/workflows
      - name: Run rules tests
        run: npm run ci:test:rules
