name: On pull request

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '10'
      - run: npm ci
      - run: npm run ci:test:rules
